"""
PyScan Flask Web Application (Full System)

Main entry point for the PyScan vulnerability detection tool.
Manages blueprints, routes, security headers, error handlers, and
application lifecycle.

Security measures:
- Uploaded code is NEVER executed; only parsed with ast.parse()
- Secure filenames via werkzeug.utils.secure_filename
- Session cookies are HttpOnly and SameSite=Lax
- Security headers added to every response
- CSRF protection on all forms
- Rate limiting on login attempts

Author: PyScan Project -- BSc Cybersecurity Final Year Project
Institution: Federal University of Technology, Babura (FUTB)
"""

import os
import tempfile
from datetime import datetime
from typing import Any, Dict, List, Optional

from flask import (
    Flask,
    flash,
    g,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)
from compat import Bcrypt, CSRFProtect
from werkzeug.utils import secure_filename

from auth import auth_bp, bcrypt as auth_bcrypt
from config import Config
from dashboard import dashboard_bp
from database import (
    close_db,
    get_db,
    init_db,
    log_action,
    save_scan,
)
from detector import VulnerabilityDetector
from preprocessor import PythonPreprocessor

# Global instances for preprocessor and detector
preprocessor: PythonPreprocessor = PythonPreprocessor()
detector: VulnerabilityDetector = VulnerabilityDetector()


def allowed_file(filename: str) -> bool:
    """Check whether a filename has an allowed extension (.py)."""
    return os.path.splitext(filename)[1].lower() == ".py"


def generate_report(scan_results: Dict[str, Any]) -> str:
    """Generate a plain-text vulnerability report from scan results."""
    lines: List[str] = [
        "PyScan Vulnerability Detection Report",
        "=" * 40,
        f"File: {scan_results['filename']}",
        f"Scan Time: {scan_results['scan_time']}",
        f"Total Functions Analysed: {scan_results['total_functions']}",
        f"Vulnerable Functions: {scan_results['vulnerable_count']}",
        f"Safe Functions: {scan_results['safe_count']}",
        "",
    ]

    vulnerable_funcs: List[Dict[str, Any]] = [
        f for f in scan_results["functions"] if f["is_vulnerable"]
    ]
    safe_funcs: List[Dict[str, Any]] = [
        f for f in scan_results["functions"] if not f["is_vulnerable"]
    ]

    if vulnerable_funcs:
        lines.append("VULNERABLE FUNCTIONS")
        lines.append("-" * 20)
        for idx, func in enumerate(vulnerable_funcs, 1):
            lines.append(
                f"[{idx}] {func['function_name']} -- Line {func['start_line']}"
            )
            lines.append(f"    Risk Level: {func['risk_level']}")
            lines.append(f"    Confidence: {func['confidence_percent']}%")
            lines.append(f"    CWE Category: {func['cwe_category']}")
            tokens = " | ".join(func["suspicious_tokens"])
            lines.append(f"    Suspicious Tokens: {tokens}")
            lines.append("")

    if safe_funcs:
        lines.append("SAFE FUNCTIONS")
        lines.append("-" * 14)
        for func in safe_funcs:
            lines.append(
                f"{func['function_name']} -- Line {func['start_line']} -- "
                f"Confidence: {func['confidence_percent']}%"
            )
        lines.append("")

    lines.append(
        "Generated by PyScan | BSc Cybersecurity Final Year Project | FUTB"
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Application Factory
# ---------------------------------------------------------------------------

def create_app() -> Flask:
    """
    Create and configure the Flask application instance.

    Returns
    -------
    Flask
        Configured Flask application.
    """
    app = Flask(__name__)
    app.config.from_object(Config)

    # Ensure required directories exist
    os.makedirs(Config.UPLOAD_FOLDER, exist_ok=True)
    os.makedirs("database", exist_ok=True)
    os.makedirs("models", exist_ok=True)

    # Initialise extensions
    auth_bcrypt.init_app(app)
    csrf = CSRFProtect(app)

    # Register blueprints
    app.register_blueprint(auth_bp)
    app.register_blueprint(dashboard_bp)

    # Routes
    @app.route("/")
    def index() -> Any:
        if "user_id" in session:
            return redirect(url_for("dashboard.index"))
        return redirect(url_for("about"))

    @app.route("/about")
    def about() -> Any:
        return render_template("about.html")

    @app.route("/scan")
    def scan_page() -> Any:
        if "user_id" not in session:
            flash("Please log in to scan files.", "warning")
            return redirect(url_for("auth.login"))
        return render_template("index.html")

    @app.route("/scan", methods=["POST"])
    def scan_process() -> Any:
        import zipfile

        if "user_id" not in session:
            flash("Please log in to scan files.", "warning")
            return redirect(url_for("auth.login"))

        uploaded_files = request.files.getlist("file") or request.files.getlist("files")
        if not uploaded_files or (len(uploaded_files) == 1 and uploaded_files[0].filename == ""):
            flash("No files or folder selected.", "warning")
            return redirect(url_for("scan_page"))

        user_id: int = session["user_id"]
        first_fname = uploaded_files[0].filename.replace("\\", "/").strip("/")
        display_name = first_fname.split("/")[0] if ("/" in first_fname and len(uploaded_files) > 1) else (secure_filename(uploaded_files[0].filename) or "Upload Batch")

        all_functions: List[Dict[str, Any]] = []
        unique_files: set = set()

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                for file_item in uploaded_files:
                    if not file_item or not file_item.filename:
                        continue
                    fname = file_item.filename
                    clean_name = fname.replace("\\", "/").lstrip("/")
                    is_zip = clean_name.lower().endswith(".zip")
                    is_py = clean_name.lower().endswith(".py")

                    if not (is_py or is_zip):
                        continue

                    target_path = os.path.join(tmpdir, clean_name)
                    os.makedirs(os.path.dirname(target_path), exist_ok=True)
                    file_item.save(target_path)

                    if is_zip:
                        zip_extract_dir = os.path.join(tmpdir, f"zip_extract_{len(all_functions)}")
                        os.makedirs(zip_extract_dir, exist_ok=True)
                        try:
                            with zipfile.ZipFile(target_path, "r") as zf:
                                zf.extractall(zip_extract_dir)
                            zip_funcs = preprocessor.preprocess_directory(zip_extract_dir)
                            all_functions.extend(zip_funcs)
                            for zf_func in zip_funcs:
                                unique_files.add(zf_func.get("filename", clean_name))
                        except Exception as zip_err:
                            flash(f"Error processing zip file {clean_name}: {zip_err}", "warning")
                    elif is_py:
                        unique_files.add(clean_name)
                        try:
                            funcs = preprocessor.preprocess_file(target_path)
                            for f in funcs:
                                f["filename"] = clean_name
                            all_functions.extend(funcs)
                        except Exception:
                            pass

                if not all_functions:
                    flash("No valid Python functions found in uploaded file(s) or folder.", "warning")
                    return redirect(url_for("scan_page"))

                file_map: Dict[str, str] = {}
                results: List[Dict[str, Any]] = []
                cwe_summary: Dict[str, int] = {}
                for func in all_functions:
                    raw_fn_file = func.get("filename", "target.py")
                    if raw_fn_file not in file_map:
                        file_map[raw_fn_file] = f"File {len(file_map) + 1}"

                    prediction = detector.predict(func)
                    prediction["filename"] = file_map[raw_fn_file]
                    results.append(prediction)

                    cwe = prediction.get("cwe_category", "N/A")
                    if prediction.get("is_vulnerable") and cwe != "N/A":
                        cwe_summary[cwe] = cwe_summary.get(cwe, 0) + 1

                vulnerable_count = sum(1 for r in results if r["is_vulnerable"])
                safe_count = len(results) - vulnerable_count
                high_risk_count = sum(1 for r in results if r["risk_level"] == "HIGH")

                files_count = max(len(unique_files), 1)
                anonymized_display_name = f"Anonymized Target ({files_count} file{'s' if files_count > 1 else ''})"

                scan_results: Dict[str, Any] = {
                    "filename": anonymized_display_name,
                    "scan_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "total_functions": len(results),
                    "vulnerable_count": vulnerable_count,
                    "safe_count": safe_count,
                    "high_risk_count": high_risk_count,
                    "files_scanned": files_count,
                    "cwe_summary": cwe_summary,
                    "functions": results,
                }

                save_scan(user_id, anonymized_display_name, scan_results)
                session["scan_results"] = scan_results
                log_action(
                    user_id,
                    "SCAN_COMPLETED",
                    request.remote_addr,
                    f"Target: Anonymized Target ({files_count} files), Vulnerable: {vulnerable_count}",
                )

        except Exception as exc:
            flash(f"An error occurred during scanning: {exc}", "danger")
            return redirect(url_for("scan_page"))

        return redirect(url_for("results"))

    @app.route("/results")
    def results() -> Any:
        if "user_id" not in session:
            flash("Please log in to view results.", "warning")
            return redirect(url_for("auth.login"))

        scan_results: Optional[Dict[str, Any]] = session.get("scan_results")
        if not scan_results:
            flash("No scan results available. Please upload a file first.", "info")
            return redirect(url_for("scan_page"))

        summary_color = "danger" if scan_results["vulnerable_count"] > 0 else "success"
        return render_template(
            "results.html",
            scan_results=scan_results,
            summary_color=summary_color,
            from_dashboard=False,
        )

    @app.route("/download-report")
    def download_report() -> Any:
        if "user_id" not in session:
            flash("Please log in to download reports.", "warning")
            return redirect(url_for("auth.login"))

        scan_results: Optional[Dict[str, Any]] = session.get("scan_results")
        if not scan_results:
            flash("No scan results available to download.", "info")
            return redirect(url_for("scan_page"))

        report_text = generate_report(scan_results)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"pyscan_report_{timestamp}.txt"

        with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as tmp:
            tmp.write(report_text)
            tmp_path = tmp.name

        try:
            return send_file(
                tmp_path,
                as_attachment=True,
                download_name=report_filename,
                mimetype="text/plain",
            )
        finally:
            try:
                os.remove(tmp_path)
            except OSError:
                pass

    # Security Headers
    @app.after_request
    def set_security_headers(response: Any) -> Any:
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["X-XSS-Protection"] = "1; mode=block"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
        return response

    # Context Processors
    @app.context_processor
    def inject_user() -> Dict[str, Any]:
        return {
            "is_logged_in": "user_id" in session,
            "username": session.get("username"),
            "role": session.get("role"),
        }

    # Error Handlers
    @app.errorhandler(404)
    def not_found(error: Any) -> Any:
        return render_template("error.html", code=404, title="Page Not Found",
                               message="The page you are looking for does not exist."), 404

    @app.errorhandler(403)
    def forbidden(error: Any) -> Any:
        return render_template("error.html", code=403, title="Access Denied",
                               message="You do not have permission to access this resource."), 403

    @app.errorhandler(429)
    def too_many_requests(error: Any) -> Any:
        return render_template("error.html", code=429, title="Too Many Requests",
                               message="Please slow down and try again later."), 429

    @app.errorhandler(500)
    def server_error(error: Any) -> Any:
        flash("An internal server error occurred. Please try again.", "danger")
        return render_template("error.html", code=500, title="Server Error",
                               message="Something went wrong on our end. Please try again."), 500

    # Register teardown
    app.teardown_appcontext(close_db)

    # Initialise database
    with app.app_context():
        init_db()
        _seed_admin(app)

    return app


def _seed_admin(app: Flask) -> None:
    """Seed default admin account if no users exist."""
    from database import get_user_by_email

    if get_user_by_email("admin@pyscan.local") is None:
        db = get_db()
        password_hash = auth_bcrypt.generate_password_hash("Admin@PyScan2024").decode("utf-8")
        db.execute(
            """
            INSERT INTO users (username, email, password_hash, role)
            VALUES (?, ?, ?, 'admin')
            """,
            ("admin", "admin@pyscan.local", password_hash),
        )
        db.commit()
        print("[PyScan] Default admin account created: admin@pyscan.local / Admin@PyScan2024")


# ---------------------------------------------------------------------------
# Module Instance
# ---------------------------------------------------------------------------

app = create_app()


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
